# Generated by Django 3.1.3 on 2020-11-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
