# Generated by Django 3.1.3 on 2020-11-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20201125_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='best_movie_id',
            new_name='best_movie_id_1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='best_movie_title',
            new_name='best_movie_title_1',
        ),
        migrations.AddField(
            model_name='profile',
            name='best_movie_id_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='best_movie_id_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='best_movie_title_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='best_movie_title_3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
