# Generated by Django 3.1.3 on 2020-11-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_profile_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='best_movie_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='best_movie_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
