# Generated by Django 3.1.3 on 2020-11-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20201124_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='best_movie_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
