# Generated by Django 3.1.3 on 2020-11-25 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0002_favoritemovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovie',
            name='favorite_user',
            field=models.ManyToManyField(related_name='favorite_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
